### PR TITLE
add openssl soft work supporting for cipher and digest

### PR DESCRIPTION
**Pull request by yekai123123**

### CODE REVIEW

**Comment by gaozhangfei** [comment]
is this sync to internal code, why need change api
build fail here, 
uadk_cipher.c:816:23: error: ‘UADK_DO_SOFT’ undeclared (first use in this function)

**Comment by gaozhangfei** [comment]
1, why change api?

2, can not start nginx
linaro@ubuntu:/usr/local/nginx$ sudo sbin/nginx 
hisi sec init Kunpeng920!
failed to setup async event notification.
failed to setup async event notification.
failed to setup async event notification.
failed to setup async event notification.
failed to setup async event notification.
nginx: [emerg] SSL_CTX_new() failed (SSL: error:2406C06C:random number generator:RAND_DRBG_instantiate:error instantiating drbg error:2406B072:random number generator:RAND_DRBG_generate:in error state error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy error:2406C06C:random number generator:RAND_DRBG_instantiate:error instantiating drbg error:2406B072:random number generator:RAND_DRBG_generate:in error state error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy error:2406B072:random number generator:RAND_DRBG_generate:in error state error:2406C06C:random number generator:RAND_DRBG_instantiate:error instantiating drbg error:2406B072:random number generator:RAND_DRBG_generate:in error state error:2406C06E:random number generator:RAND_DRBG_instantiate:error retrieving entropy error:2406C06C:random number generator:RAND_DRBG_instantiate:error instantiating drbg error:2406B072:random number generator:RAND_DRBG_generate:in error state err:2406c06e:24:6c:6e err:240)

**Comment by gaozhangfei** [comment]
nginx can not work

**Comment by yekai123123** [comment]
need closed.

**Pull request closed without merging**
